var data;
data = [
    {analogie:"une saison", valeurAnalogie:"le printemps",  image:"./illustrations/printemps.jpg", explication:"Parce que je suis né en avril et donc au printemps. De plus, il ne fait ni trop chaud ni trop froid au printemps. En effet, les jours s'allongent, les températures augmentent et permettent de passer davantage de temps à l'extérieur. Sauf que les températures ne sont pas aussi fortes par rapport à l’été ce qui rend les sorties plus agréables selon moi."},
    
    {analogie:"une chanson", valeurAnalogie:"Bâtard de Stromae", image:"./illustrations/musique.jpg", explication:"Parce que quand j’étais petite je l’écoutais en boucle avec mon mp3. De plus, je me reconnais dans les paroles, en effet cette chanson parle du fait d’avoir du mal à trouver sa place en tant que personne métisse de peau. Le mot « Bâtard » pourrait faire référence à l'individualisme. Dans le sens ou, n'importe quel humain ne devrait représenter que lui-même, et que ses origines ne doivent pas l'introduire dans une partialité qui engendrera une répartition sociale et influencera ses choix vers le pire. Aucune origine ne justifie un mal dans le monde. Stromae évoque également les jugements constants des gens qui veulent mettre les autres dans une case bien précise. L'instrumentale de la chanson « Bâtard » est électro par excellence, Stromae nous invite à danser sur ses chansons tout en nous pensons à méditer sur des sujets très sérieux qui touchent à toutes les sociétés."},
    
    {analogie:"un instrument de musique", valeurAnalogie:"une guitare", image:"./illustrations/guitare.jpg", explication:"Parce que j’en joue depuis mes 9 ans, et que j’adore en faire. De plus, la guitare offre une multitude d’avantages: elle est assez simple à comprendre, les premiers pas sont assez faciles à suivre et la progression dans la pratique peut être assez rapide pour atteindre un bon niveau. C’est un instrument qui peut se jouer n’importe où, avec n’importe qui et vous pouvez reproduire beaucoup de morceaux à l’oreille. De nombreuses partitions et tablatures sont disponibles sur Internet, avec de nombreux tutos. Et enfin, il n’y a pas d’âge pour commencer la guitare."},
    
    {analogie:"un vêtement", valeurAnalogie:"un sweat à capuche", image:"./illustrations/vêtements.jpg", explication:"Parce que c’est un vêtement polyvalent qui se porte en ville, en week-end ou au travail. Indémodable, il permet de combiner les couleurs facilement, en plus d’être personnalisable au vu des nombreux motifs différents disponibles. De plus, il est très confortable à porter, je pense d’ailleurs que c’est la raison pour laquelle je l'apprécie le plus."},
    
    {analogie:"un producteur", valeurAnalogie:"3RACHA", image:"./illustrations/producteur.jpg", explication:"Parce que c’est un groupe de producteur assez jeune, qui parle donc de choses dont je peux relater. Leurs styles sont différents mais se complètent très bien, ce qui permet d’écouter des choses plus variées que s’il s'agissait d’une seule personne. Les paroles de leurs chansons sont très inspirantes et abordent des sujets précis tels que la période entre adolescence et l'âge adulte, la solitude etc."},
    
    {analogie:"un film", valeurAnalogie:"Black Panther", image:"./illustrations/film.jpg", explication:"Parce qu’il s’agit de mon film préféré. Des visuels incroyables, à la représentation de la culture noir africaine avec le premier super-héros noir du Marvel Cinematic Universe, ce film ma tout simplement fait vibrer. J’ai toujours été une grande fan des films Marvel, mais celui-ci est de loin mon préféré. De plus l’histoire est touchante, encore plus dans le numéro deux, même si le un reste meilleur, notamment grâce au jeu d’acteur de Chadwick Boseman."},
    
    {analogie:"un paysage", valeurAnalogie:"une plage", image:"./illustrations/martinique.jpg", explication:"Parce que la vue de la plage m’apaise. En effet, d’après plusieurs études scientifiques, notre cerveau réagit différemment selon les paysages regardés. Et le paysage qui crée le plus d’apaisement c’est la plage ! Pour moi la plage c’est : les beaux paysages, la chaleur du soleil sur la peau, s'allonger dans le sable et profiter du soleil, une baignade rafraîchissante, un après-midi entre amis ou en famille. Quand je pense à la plage, j’imagine plus particulièrement une plage en Martinique, dont je suis originaire, le simple bruit des vagues peut m’endormir alors même que je suis insomniaque."}
];